'use client';
import {useState} from 'react';
import {useRouter} from 'next/navigation';
import type {Contract} from '@/lib/contract-domain';
const decimal=(cents:string)=>`${BigInt(cents)/100n},${(BigInt(cents)%100n).toString().padStart(2,'0')}`;
function money(value:FormDataEntryValue|null){const s=String(value??'').trim();if(!/^\d{1,13}(?:,\d{1,2})?$/.test(s))throw Error('Use valores sem separador de milhar, como 1250,50.');const [integer,fraction='']=s.split(',');return (BigInt(integer)*100n+BigInt(fraction.padEnd(2,'0'))).toString();}
export function ContractEditor({projectId,contract}:{projectId:string;contract?:Contract}){
 const [receipts,setReceipts]=useState(contract?.receipts??[]),[busy,setBusy]=useState(false),[message,setMessage]=useState('');const router=useRouter();
 return <details className="mb-5 rounded-xl border border-[var(--border)] bg-white p-5"><summary className="cursor-pointer font-semibold">{contract?'Atualizar contrato e recebimentos':'Informar contrato'}</summary><form className="mt-4" onSubmit={async event=>{event.preventDefault();const data=new FormData(event.currentTarget);setBusy(true);setMessage('');try{
 const value={revision:contract?.revision??'0',totalCents:money(data.get('total')),reference:String(data.get('reference')),reason:String(data.get('reason')),receipts:receipts.map(r=>({id:r.id,amountCents:money(data.get('amount-'+r.id)),receivedOn:String(data.get('date-'+r.id)),reference:String(data.get('reference-'+r.id)),voided:data.get('void-'+r.id)==='on'}))};
 const response=await fetch(`/api/projects/${projectId}/contract`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(value)});const result=await response.json();if(!response.ok)throw Error(result.error);setMessage('Contrato salvo.');router.refresh();
 }catch(e){setMessage(e instanceof Error?e.message:'Não foi possível salvar.');}finally{setBusy(false);}}}><fieldset disabled={busy} className="space-y-4">
 <label className="block text-sm">Referência do contrato<input name="reference" defaultValue={contract?.reference??''} required minLength={3} maxLength={200} className="mt-1 block w-full rounded border p-2"/></label>
 <label className="block text-sm">Valor total contratado (R$)<input name="total" inputMode="decimal" placeholder="1250,50" defaultValue={contract?decimal(contract.totalCents):''} required className="mt-1 block w-full rounded border p-2"/></label>
 <p className="text-sm">Registre somente valores já recebidos deste contrato. Para corrigir um recebimento, edite-o ou marque Anulado; as versões anteriores ficam no histórico.</p>
 {receipts.map((r,index)=><div key={r.id} className="grid gap-3 rounded border p-3 sm:grid-cols-2"><div className="flex justify-between sm:col-span-2"><p className="font-semibold">Recebimento {index+1}</p>{!contract?.receipts.some(saved=>saved.id===r.id)&&<button type="button" className="text-sm underline" onClick={()=>setReceipts(receipts.filter(item=>item.id!==r.id))}>Descartar novo recebimento</button>}</div><label className="text-sm">Valor recebido (R$)<input aria-label={`Valor recebido ${index+1}`} name={'amount-'+r.id} defaultValue={decimal(r.amountCents)} required inputMode="decimal" className="mt-1 block w-full rounded border p-2"/></label><label className="text-sm">Data do recebimento<input aria-label={`Data do recebimento ${index+1}`} type="date" name={'date-'+r.id} defaultValue={r.receivedOn} required className="mt-1 block w-full rounded border p-2"/></label><label className="text-sm sm:col-span-2">Referência do recebimento<input aria-label={`Referência do recebimento ${index+1}`} name={'reference-'+r.id} defaultValue={r.reference} required minLength={3} maxLength={200} className="mt-1 block w-full rounded border p-2"/></label><label className="text-sm"><input type="checkbox" name={'void-'+r.id} defaultChecked={r.voided}/> Anulado</label></div>)}
 <button type="button" disabled={receipts.length>=200} className="rounded border px-3 py-2 text-sm" onClick={()=>setReceipts([...receipts,{id:crypto.randomUUID(),amountCents:'0',receivedOn:'',reference:'',voided:false}])}>Adicionar recebimento do contrato</button>
 <label className="block text-sm">Motivo desta atualização<input name="reason" required minLength={3} maxLength={500} className="mt-1 block w-full rounded border p-2"/></label>
 <button className="rounded-lg bg-[var(--brand)] px-4 py-2 font-semibold text-white">{busy?'Salvando…':'Salvar contrato'}</button>
 </fieldset>{message&&<p role="status" className="mt-3 text-sm">{message}</p>}</form></details>;
}
