'use client';
import {useState} from 'react';
import {useRouter} from 'next/navigation';
import Link from 'next/link';
import {cashMoney} from '@/lib/cash-domain';
import {invoiceCashTotals,invoicePaymentIssues,possibleExistingPayments,type InvoiceCashRow,type ExistingPayment} from '@/lib/fiscal-payment-domain';
type Project={id:string;title:string};
async function save(body:unknown){const response=await fetch('/api/fiscal-payments',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const result=await response.json();if(!response.ok)throw Error(result.error??'Não foi possível salvar.');return result as {confirmed?:number;skipped?:number};}
export function FiscalPayments({notes,payments,basisHash,projects}:{notes:InvoiceCashRow[];payments:ExistingPayment[];basisHash:string;projects:Project[]}){
 const router=useRouter();const [reason,setReason]=useState('');const [checked,setChecked]=useState(false);const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');
 const totals=invoiceCashTotals(notes),pending=notes.filter(n=>!n.deleted&&!n.declaration),eligible=pending.filter(n=>!possibleExistingPayments(n,payments).length);
 async function confirmAll(){setBusy(true);setMessage('');try{const result=await save({operation:'confirm-all',basisHash,reason,confirmed:checked});setMessage(`${result.confirmed} pagamentos confirmados. ${result.skipped} notas aguardam conciliação com pagamentos existentes.`);setChecked(false);router.refresh();}catch(error){setMessage(error instanceof Error?error.message:'Não foi possível salvar.');}finally{setBusy(false);}}
 return <>
  <section className="my-5 rounded-lg border bg-white p-5"><h2 className="text-xl font-bold">Pagamentos declarados nas notas fiscais</h2><p className="mt-3 text-2xl font-bold">{cashMoney(totals.totalCents)}</p><p className="mt-2 text-sm">{totals.count} notas confirmadas · {totals.undated} sem data de pagamento · {totals.unassigned} sem projeto · {totals.changed} com dados fiscais alterados.</p><p className="mt-2 text-sm">Este é o total das declarações. Pagamentos já vinculados são contados uma única vez no caixa; possíveis duplicidades ficam pendentes de conciliação.</p></section>
  {pending.length>0&&<section className="my-5 rounded-lg border bg-white p-5"><h2 className="font-bold">Confirmar notas ainda não declaradas</h2><p className="mt-2 text-sm">{eligible.length} notas disponíveis, no total de {cashMoney(eligible.reduce((sum,n)=>sum+BigInt(n.amountCents),0n).toString())}. {pending.length-eligible.length} precisam de conferência por terem pagamento do mesmo valor.</p><p className="mt-2 text-sm">O projeto declarado na nota será mantido. A data de emissão não será usada como data de pagamento. Notas já confirmadas ou revertidas não serão alteradas.</p><label className="mt-3 block text-sm">Justificativa da confirmação<textarea value={reason} onChange={e=>setReason(e.target.value)} minLength={3} maxLength={500} className="mt-1 w-full rounded border p-2"/></label><label className="mt-3 flex gap-2 text-sm"><input type="checkbox" checked={checked} onChange={e=>setChecked(e.target.checked)}/>Confirmo que os valores dessas notas foram pagos e representam saídas de dinheiro.</label><button onClick={confirmAll} disabled={busy||!checked||reason.trim().length<3||!eligible.length} className="mt-4 rounded bg-[var(--brand)] px-4 py-2 text-white disabled:opacity-50">{busy?'Salvando…':'Confirmar pagamentos das notas'}</button></section>}
  {message&&<p role="status" className="my-4 rounded border p-3">{message}</p>}
  <div className="space-y-3">{notes.map(note=><InvoicePayment key={`${note.id}:${note.declaration?.revision??'0'}:${note.noteRevision}`} note={note} payments={payments} projects={projects}/>)}</div>
 </>;
}
function InvoicePayment({note,payments,projects}:{note:InvoiceCashRow;payments:ExistingPayment[];projects:Project[]}){
 const d=note.declaration,router=useRouter();const [projectId,setProject]=useState(d?d.projectId??'':note.projectId??'');const [paidOn,setPaidOn]=useState(d?.paidOn??'');const [paymentEntryId,setPayment]=useState(d?.paymentEntryId??'');const [separatePayment,setSeparate]=useState(d?.separatePayment??false);const [reason,setReason]=useState('');const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');
 const candidates=possibleExistingPayments(note,payments),issues=invoicePaymentIssues(note,payments);
 async function submit(status:'confirmado'|'revertido'){setBusy(true);try{await save({operation:'save',id:note.id,revision:d?.revision??'0',status,projectId:projectId||null,paidOn:paidOn||null,paymentEntryId:paymentEntryId||null,separatePayment,reason});setMessage('Confirmação salva no histórico.');router.refresh();}catch(error){setMessage(error instanceof Error?error.message:'Não foi possível salvar.');}finally{setBusy(false);}}
 return <details className="rounded-lg border bg-white p-4"><summary className="cursor-pointer font-semibold">NF {note.number} · {cashMoney(d?.status==='confirmado'?d.amountCents:note.amountCents)} · {d?.status==='confirmado'?'Pagamento confirmado pelo proprietário':d?.status==='revertido'?'Confirmação revertida':'Pagamento não declarado'}</summary>
 <div className="mt-3 space-y-3 text-sm"><p>Emissão: {note.issueDate.split('-').reverse().join('/')} · {note.projectTitle??'Sem projeto declarado'}. {note.deleted?'Nota excluída do universo fiscal; declaração histórica preservada.':''}</p><Link className="underline text-[var(--brand)]" href={`/notas-fiscais?nota=${encodeURIComponent(note.id)}`}>Ver nota fiscal e origem</Link>{d?.projectId&&<Link className="ml-4 underline text-[var(--brand)]" href={`/projetos/${encodeURIComponent(d.projectId)}`}>Ver caixa e narrativa do projeto</Link>}
 {d&&<p>R{d.revision} · {d.actor} · {d.reason} · Data de pagamento: {d.paidOn?.split('-').reverse().join('/')??'Não informada'}.</p>}{issues.map(issue=><p key={issue} className="font-semibold text-amber-800">{issue}</p>)}
 {candidates.length>0&&<p>Há {candidates.length} pagamento(s) do mesmo valor. Confira antes de somar uma nova saída.</p>}
 <label className="block">Projeto do pagamento<select value={projectId} onChange={e=>{setProject(e.target.value);setPayment('');}} className="ml-2 max-w-full rounded border p-2"><option value="">Sem projeto / a conciliar</option>{projects.map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</select></label>
 <label className="block">Pagamento já lançado<select value={paymentEntryId} onChange={e=>{const p=payments.find(p=>p.id===e.target.value);setPayment(e.target.value);if(p)setPaidOn(p.paidOn??'');}} className="ml-2 max-w-full rounded border p-2"><option value="">Registrar declaração independente</option>{candidates.filter(p=>p.projectId===projectId&&p.confirmed).map(p=><option key={p.id} value={p.id}>{p.description} · {p.paidOn}</option>)}</select></label>
 <label className="block">Data do pagamento, se conhecida<input type="date" value={paidOn} disabled={Boolean(paymentEntryId)} onChange={e=>setPaidOn(e.target.value)} className="ml-2 rounded border p-2"/></label>
 {candidates.length>0&&!paymentEntryId&&<label className="flex gap-2"><input type="checkbox" checked={separatePayment} onChange={e=>setSeparate(e.target.checked)}/>Conferi: esta saída é distinta dos pagamentos existentes do mesmo valor.</label>}
 <label className="block">Motivo<input value={reason} onChange={e=>setReason(e.target.value)} minLength={3} maxLength={500} className="mt-1 w-full rounded border p-2"/></label>
 <button disabled={busy||note.deleted||reason.trim().length<3} onClick={()=>submit('confirmado')} className="rounded bg-[var(--brand)] px-4 py-2 text-white disabled:opacity-50">Salvar confirmação</button>{d?.status==='confirmado'&&<button disabled={busy||reason.trim().length<3} onClick={()=>submit('revertido')} className="ml-3 rounded border px-4 py-2 disabled:opacity-50">Reverter confirmação</button>}{message&&<p role="status">{message}</p>}
 </div></details>;
}
